version: '3.8'

services:
  postgres:
    image: postgres:latest
    networks:
      - backend
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env.docker

  deedni-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge
